### ISSUE TITLE
solaris compile error: resource.h:146: error: field ‘ru_utime’ has incomplete type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chandanpasunoori/redis#472]
```
Hi, 

What version of Redis you are using, in what kind of Operating System?
redis-1.2.6, redis-2.0.4, redis-2.2.0, redis-2.2.1
root@comp:~ # uname -a
SunOS comp 5.10 Generic_127128-11 i86pc i386 i86pc Solaris

What is the problem you are experiencing?
* make error:
What is the expected output? What do you see instead?
In file included from /usr/include/sys/vnode.h:45,
                 from /usr/include/sys/stream.h:22,
                 from /usr/include/netinet/in.h:66,
                 from /usr/include/sys/socket.h:45,
                 from anet.c:34:
/usr/include/sys/resource.h:146: error: field ‘ru_utime’ has incomplete type
/usr/include/sys/resource.h:147: error: field ‘ru_stime’ has incomplete type
make[1]: *** [anet.o] Error 1
make: *** [32bit] Error 2

What steps will reproduce the problem?
* download any redis version, try to compile on SunOS 5.10

Please provide any additional information below.
root@comp:~ # gcc --version
gcc (GCC) 4.3.4

this is a duplicate of: http://code.google.com/p/redis/issues/detail?id=90
but that issue is closed.

kind regards
```

Original issue reported on code.google.com by `marziz...@gmail.com` on 25 Feb 2011 at 6:17
