### ISSUE TITLE
doesn;t compile on MAC OS X Tiger 10.4.11

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chandanpasunoori/redis#70]
```
What steps will reproduce the problem?
1. /usr/src/redis-1.01 $ sudo make
2.
3.

What is the expected output? What do you see instead?
cc -c -std=c99 -pedantic -O2 -Wall -W -g -rdynamic -ggdb   redis.c
i686-apple-darwin8-gcc-4.0.1: unrecognized option '-rdynamic'
redis.c:44:22: error: execinfo.h: No such file or directory
redis.c: In function 'updateSlavesWaitingBgsave':
redis.c:3980: error: storage size of 'buf' isn't known
redis.c:3988: warning: implicit declaration of function 'fstat64'
redis.c:3980: warning: unused variable 'buf'
redis.c: In function 'getMcontextEip':
redis.c:4309: error: 'struct mcontext' has no member named '__ss'
redis.c: In function 'segvHandler':
redis.c:4361: warning: implicit declaration of function 'backtrace'
redis.c:4366: warning: implicit declaration of function 'backtrace_symbols'
redis.c:4366: warning: assignment makes pointer from integer without a cast
make: *** [redis.o] Error 1

redis 1.01  on MAC book OS X Tiger 10.4.11

tried with mac ports same error

thanks for help


```

Original issue reported on code.google.com by `nathan.sharkey` on 9 Oct 2009 at 3:19
